### ISSUE TITLE
Startet nicht :-(

### ISSUE THREAD

**Issue by obcode** [ob-vss-ss18/ppl-client#20]
Ich habe wie in der README beschrieben, `node_modules` entpackt.
Die Eingabe von `npm run electron` ergab folgenden Fehler:

```
> angular-electron@0.0.0 electron /Users/obraun/tmp/ppl-client
> ng build && electron .

Date: 2018-06-26T05:57:44.538Z
Hash: 49c39b4449c6e5665258
Time: 4643ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 3.89 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 277 bytes [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 297 bytes [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 16.2 kB [initial] [rendered]

ERROR in ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--8-3!./src/styles.scss
Module build failed: Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (64)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.8.3
    at module.exports (/Users/obraun/tmp/ppl-client/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/obraun/tmp/ppl-client/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/obraun/tmp/ppl-client/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
ERROR in multi ./node_modules/bootstrap/dist/css/bootstrap.min.css ./src/styles.scss
Module not found: Error: Can't resolve '/Users/obraun/tmp/ppl-client/node_modules/bootstrap/dist/css/bootstrap.min.css' in '/Users/obraun/tmp/ppl-client'
ERROR in src/app/app.module.ts(13,25): error TS2307: Cannot find module '@ng-bootstrap/ng-bootstrap'.
src/app/customer/customer.component.ts(2,31): error TS2307: Cannot find module '@ng-bootstrap/ng-bootstrap'.
src/app/customer/customer.component.ts(3,24): error TS2307: Cannot find module 'apollo-angular'.
src/app/customer/customer.component.ts(4,17): error TS2307: Cannot find module 'graphql-tag'.
src/app/equipment/equipment.component.ts(2,24): error TS2307: Cannot find module 'apollo-angular'.
src/app/equipment/equipment.component.ts(3,17): error TS2307: Cannot find module 'graphql-tag'.
src/app/graphql.module.ts(7,38): error TS2307: Cannot find module 'apollo-angular'.
src/app/graphql.module.ts(8,42): error TS2307: Cannot find module 'apollo-angular-link-http'.
src/app/graphql.module.ts(9,31): error TS2307: Cannot find module 'apollo-cache-inmemory'.
src/app/login/login.component.ts(4,24): error TS2307: Cannot find module 'apollo-angular'.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-electron@0.0.0 electron: `ng build && electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-electron@0.0.0 electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/obraun/.npm/_logs/2018-06-26T05_57_44_575Z-debug.log
```

**Comment by Evyl1303** [comment]
Geht ng serve?

**Comment by Evyl1303** [comment]
Machen Sie mal noch npm i davor

**Comment by obcode** [comment]
Gleiches Problem:

````
...
Module build failed: Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (64)
````

Irgendwas mit Sass scheint das

**Comment by obcode** [comment]
ok, I try

**Comment by obcode** [comment]
warum die node_modules eigentlich gepackt mit rein?

**Comment by obcode** [comment]
`npm i` endet auch erfolglos:

```
> fsevents@1.2.3 install /Users/obraun/tmp/ppl-client/node_modules/fsevents
> node install

[fsevents] Success: "/Users/obraun/tmp/ppl-client/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> electron@1.8.6 postinstall /Users/obraun/tmp/ppl-client/node_modules/electron
> node install.js

Downloading SHASUMS256.txt
[============================================>] 100.0% of 5.74 kB (5.74 kB/s)

> angular-electron@0.0.0 postinstall /Users/obraun/tmp/ppl-client
> ng build --aot -prod

Date: 2018-06-26T06:08:04.619Z
Hash: 514582bd300fb4bd1a4f
Time: 4514ms
chunk {0} styles.736028d8bf9819c6e65c.bundle.css (styles) 140 kB [initial] [rendered]
chunk {1} polyfills.997d8cc03812de50ae67.bundle.js (polyfills) 84 bytes [initial] [rendered]
chunk {2} main.ee32620ecd1edff94184.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.318b50c57b4eba3d437b.bundle.js (inline) 796 bytes [entry] [rendered]

ERROR in ./src/styles.scss
Module build failed: Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (64)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.8.3
    at module.exports (/Users/obraun/tmp/ppl-client/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/obraun/tmp/ppl-client/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/obraun/tmp/ppl-client/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
ERROR in Module build failed: Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (64)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.8.3
    at module.exports (/Users/obraun/tmp/ppl-client/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/obraun/tmp/ppl-client/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/obraun/tmp/ppl-client/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
ERROR in ./src/styles.scss
Module build failed: ModuleBuildError: Module build failed: Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (64)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.8.3
    at module.exports (/Users/obraun/tmp/ppl-client/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/obraun/tmp/ppl-client/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/obraun/tmp/ppl-client/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at runLoaders (/Users/obraun/tmp/ppl-client/node_modules/webpack/lib/NormalModule.js:195:19)
    at /Users/obraun/tmp/ppl-client/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/obraun/tmp/ppl-client/node_modules/loader-runner/lib/LoaderRunner.js:170:18
    at loadLoader (/Users/obraun/tmp/ppl-client/node_modules/loader-runner/lib/loadLoader.js:27:11)
    at iteratePitchingLoaders (/Users/obraun/tmp/ppl-client/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/obraun/tmp/ppl-client/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/obraun/tmp/ppl-client/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/Users/obraun/tmp/ppl-client/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/obraun/tmp/ppl-client/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/obraun/tmp/ppl-client/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/obraun/tmp/ppl-client/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/Users/obraun/tmp/ppl-client/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/obraun/tmp/ppl-client/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/obraun/tmp/ppl-client/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/obraun/tmp/ppl-client/node_modules/webpack/lib/NormalModule.js:182:3)
    at NormalModule.build (/Users/obraun/tmp/ppl-client/node_modules/webpack/lib/NormalModule.js:275:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-electron@0.0.0 postinstall: `ng build --aot -prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-electron@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/obraun/.npm/_logs/2018-06-26T06_08_04_670Z-debug.log
```

**Comment by Evyl1303** [comment]
updaten Sie mal

**Comment by obcode** [comment]
Leider immer noch

**Comment by Evyl1303** [comment]
Ich hab grad die Readme geupdatet. Bei uns geht's

Wenn das nicht geht was da drin steht, weiß ich leider nicht was das Problem ist :/

**Comment by Evyl1303** [comment]
Könnte daran liegen:
Module build failed: Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (64)
